language: node_js
services:
- redis-server
node_js:
- node
- '6'
before_install:
- openssl aes-256-cbc -K $encrypted_4637da4e0342_key -iv $encrypted_4637da4e0342_iv
  -in .travis/deploy_key.enc -out .travis/deploy_key -d
after_success:
  - eval "$(ssh-agent -s)" #start the ssh agent
  - chmod 600 .travis/deploy_key # this key should have push access
  - ssh-add .travis/deploy_key
  - git remote add deploy ssh://root@whatisadojo.xyz/srv/web-historian
  - git push deploy
