language: node_js
services:
- redis-server
node_js:
- node
before_install:
- openssl aes-256-cbc -K $encrypted_4637da4e0342_key -iv $encrypted_4637da4e0342_iv
  -in deploy_key.enc -out .travis/deploy_key -d
- echo -e "Host whatisadojo.xyz\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
- eval "$(ssh-agent -s)"
- chmod 600 .travis/deploy-key
- mv .travis/deploy-key ~/.ssh/id_rsa
- git remote add deploy ssh://git@whatisadojo.xyz/srv/git/repos/web-historian
- git push deploy
