language: node_js
services:
- redis-server
node_js:
- node
- '6'
before_install:
- openssl aes-256-cbc -K $encrypted_4637da4e0342_key -iv $encrypted_4637da4e0342_iv
  -in .travis/deploy_key.enc -out .travis/deploy_key -d
